# environment and authentication
exec dbus-update-activation-environment --systemd --all
exec systemctl --user import-environment
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# background services
exec wl-paste --type image --watch cliphist store
exec wl-paste --type text --watch cliphist store
exec_always sh -c 'killall -q waybar; waybar'
exec autotiling
exec nm-applet
exec swaync
exec swayosd-server

# autostart apps
exec vesktop
exec spotify-launcher
exec com.github.wwmm.easyeffects --gapplication-service
