# disable middle click paste
primary_selection disabled
exec wl-paste --primary --watch wl-copy --primary ""

# background services
exec wl-paste --type image --watch cliphist store
exec wl-paste --type text --watch cliphist store
exec_always sh -c 'killall -q waybar; sleep 0.8 && waybar'
exec_always nwg-dock -d -nolauncher -nows -hd 0 -l top
exec autotiling
exec nm-applet
exec swaync
exec swayosd-server

# autostart apps
exec vesktop
exec spotify-launcher
exec com.github.wwmm.easyeffectss --gapplication-service

# inputs
input "type:pointer" {
  accel_profile flat
  pointer_accel 0
}

input "type:touchpad" {
  drag_lock disabled
  dwt disabled
  natural_scroll enabled
  tap enabled
  tap_button_map lrm
}

# keymaps
input "type:keyboard" {
  xkb_layout us,br
}

# look and feel
gaps inner 8

default_border pixel 1
default_floating_border pixel 1
for_window [app_id="^.*"] border pixel 1

client.focused   #c6ba75 #c6ba75 #000000 #c6ba75 #c6ba75
client.unfocused #c6ba75 #c6ba75 #000000 #c6ba75 #c6ba7550
client.urgent    #c6ba75 #c6ba75 #000000 #c6ba75 #c6ba75
