# keyboard
set $mod Mod4
set $left h
set $down j
set $up k
set $right l

# shortcuts
set $browser prime-run firefox
set $file_manager thunar
set $term ghostty

set $menu fuzzel
set $menu_clipboard cliphist list | fuzzel --dmenu | cliphist decode | wl-copy
set $emoji_picker rofimoji

set $screenshot exec sh -c 'f=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && grimshot savecopy area $f && swappy -f $f -o $f && notify-send -i $f "Screenshot saved" $f'
set $screenshot_full exec sh -c 'f=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && grimshot savecopy output $f && swappy -f $f -o $f && notify-send -i $f "Screenshot saved" $f'

set $color_picker sh -c 'hyprpicker -a && notify-send "Color copied" "$(wl-paste)"'
