watch_stylesheet: true
watch_config: true
debug: false

komorebi:
  start_command: 'komorebic start --whkd'
  stop_command: 'komorebic stop --whkd'
  reload_command: 'komorebic stop --whkd && komorebic start --whkd'

bars:
  primary-bar:
    enabled: true
    screens: ['*']
    class_name: 'yasb-bar'

    alignment:
      position: 'top'
      center: false

    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      border_color: System

    window_flags:
      always_on_top: false
      windows_app_bar: true

    dimensions:
      width: '100%'
      height: 26

    padding:
      top: 4
      left: 2
      bottom: 2
      right: 2

    widgets:
      left: ['komorebi_workspaces', 'active_window']
      center: ['clock', 'apps']
      right: ['cpu', 'memory', 'battery', 'microphone', 'volume', 'power_menu']

widgets:
  komorebi_workspaces:
    type: 'komorebi.workspaces.WorkspaceWidget'
    options:
      label_zero_index: false
      hide_empty_workspaces: true
      hide_if_offline: false
      animation: false
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

  active_window:
    type: 'yasb.active_window.ActiveWindowWidget'
    options:
      label: '{win[title]}'
      label_icon: true
      label_icon_size: 14
      max_length: 36
      max_length_ellipsis: '…'
      monitor_exclusive: true

  clock:
    type: 'yasb.clock.ClockWidget'
    options:
      label: '{%I:%M %p %a}'
      label_alt: '{%A, %d %B %Y %H:%M}'
      callbacks:
        on_right: 'exec explorer.exe shell:AppsFolder\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App'

  apps:
    type: 'yasb.applications.ApplicationsWidget'
    options:
      label: '{data}'
      app_list:
        - { icon: "\uf0a2", launch: 'notification_center' }
        - { icon: "\ueb51", launch: 'quick_settings' }
        - { icon: "\uf422", launch: 'search' }
        - { icon: "\uf489", launch: 'wezterm' }
        - { icon: "\uf121", launch: 'code' }
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

  cpu:
    type: 'yasb.cpu.CpuWidget'
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      update_interval: 2000

  memory:
    type: 'yasb.memory.MemoryWidget'
    options:
      label: "<span>\uefc5</span> {virtual_mem_free}"
      label_alt: "<span>\uefc5</span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
        on_left: 'toggle_label'
      memory_thresholds:
        low: 25
        medium: 50
        high: 90

  battery:
    type: 'yasb.battery.BatteryWidget'
    options:
      label: '<span>{icon}</span>{percent}%'
      label_alt: '<span>{icon}</span> {percent}% | time: {time_remaining}'
      charging_options:
        icon_format: '{charging_icon}'
      status_icons:
        icon_charging: "\udb80\udc84"
        icon_critical: "\uf244"
        icon_low: "\uf243"
        icon_medium: "\uf242"
        icon_high: "\uf241"
        icon_full: "\uf240"

  microphone:
    type: 'yasb.microphone.MicrophoneWidget'
    options:
      label: '<span>{icon}</span> {level}'
      label_alt: '<span>{icon}</span> {level}'
      icons:
        normal: "\udb80\udf6c"
        muted: "\udb80\udf6d"
      callbacks:
        on_left: 'toggle_mute'
        on_middle: 'do_nothing'
        on_right: 'exec cmd.exe /c start ms-settings:sound'

  volume:
    type: 'yasb.volume.VolumeWidget'
    options:
      label: '<span>{icon}</span> {level}'
      label_alt: '{volume}'
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_right: 'exec cmd.exe /c start ms-settings:sound'

  power_menu:
    type: 'yasb.power_menu.PowerMenuWidget'
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 300
      button_row: 5
      buttons:
        lock: ["\uea75", 'Lock']
        signout: ["\uf08b", 'Sign out']
        sleep: ["\udb82\udd04", 'Sleep']
        shutdown: ["\uf011", 'Shut Down']
        restart: ["\uead2", 'Restart']
        cancel: ["\udb81\udf3a", 'Cancel']
