alias cd='z'
alias find='fd'
alias la='eza -a --color=always --group-directories-first --icons'
alias ll='eza -alh --color=always --group-directories-first --icons --git --time-style=long-iso'
alias ls='eza --color=always --group-directories-first --icons'
alias lt='eza -aT --color=always --group-directories-first --icons'
alias mirrors='sudo reflector --country $(curl ipinfo.io/country) --age 12 --latest 10 --protocol https --sort rate --save /etc/pacman.d/mirrorlist'
alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias zed='DRI_PRIME=1 zeditor'
