format = '$username$hostname$directory$all'

add_newline = false
palette = 'default'
scan_timeout = 10

[palettes.default]
accent = '#c6ba75'
blue = '#c6ba75'
purple = '#c6ba75'
yellow = '#c6ba75'
green = '#c6ba75'
cyan = '#c6ba75'
white = '#f9f9f1'
bright-blue = '#c6ba75'
bright-purple = '#c6ba75'
bright-yellow = '#c6ba75'
bright-green = '#c6ba75'
bright-cyan = '#c6ba75'
bright-white = '#f9f9f1'

[username]
format = '[$user](fg:accent)'
style_root = 'red'
show_always = true

[hostname]
format = '[@](fg:white)[$hostname](fg:accent)'
ssh_only = false

[directory]
style = "white"
format = "[$read_only]($read_only_style) [$path](fg:white) "
read_only = " 󰌾"
read_only_style = "red"
truncate_to_repo = false
truncation_length = 3
fish_style_pwd_dir_length = 1

[character]
success_symbol = '[❯](fg:white)'
