format ="$os$username$hostname$directory$all"

add_newline = false
scan_timeout = 10
palette = "tw"

[palettes.tw]
amber = "#f59e0b"
blue = "#3b82f6"
cyan = "#06b6d4"
emerald = "#10b981"
fuchsia = "#d946ef"
gray = "#6b7280"
green = "#22c55e"
indigo = "#6366f1"
lime = "#84cc16"
neutral = "#737373"
orange = "#f97316"
pink = "#ec4899"
purple = "#a855f7"
red = "#ef4444"
rose = "#f43f5e"
sky = "#0ea5e9"
slate = "#64748b"
stone = "#78716c"
teal = "#14b8a6"
violet = "#8b5cf6"
yellow = "#eab308"
zinc = "#71717a"

[character]
success_symbol = '[❯](indigo)'

[directory]
style = "indigo"
read_only = "  "
home_symbol = "󰉋 ~ "

[hostname]
ssh_only = false
ssh_symbol = " "
format = "[$ssh_symbol$hostname](white) "

[os]
disabled = false

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
NixOS = " "
openSUSE = " "
Pop = " "
Raspbian = " "
Redhat = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
format = "[$symbol$version](white)"
symbol = "📦 "
version_format = "v${minor}"
disabled = false

[username]
style_root = "red"
style_user = "indigo"
format = "[$user](indigo)@"
show_always = true
