abbr cat 'bat --paging=always --color=always'
abbr cd 'z'
abbr cp 'cp -v'
abbr find 'fd --color=always --type f --hidden --no-ignore-vcs'
abbr gs 'git status'
abbr la='eza -a --color=always --group-directories-first --icons'
abbr ll='eza -alh --color=always --group-directories-first --icons'
abbr ls='eza -al --color=always --group-directories-first --icons'
abbr lt='eza -aT --color=always --group-directories-first --icons'
abbr ripgrep 'rg --color=always --line-number --smart-case --hidden --no-heading'