# name: 'default'
# preferred_background: black
# apply the theme: fish_config theme choose default

set -U fish_color_autosuggestion 626262
set -U fish_color_command e4e4e4
set -U fish_color_comment 888888
set -U fish_color_error 585858
set -U fish_color_escape bryellow
set -U fish_color_keyword ffffff
set -U fish_color_operator bryellow
set -U fish_color_param d0d0d0
set -U fish_color_quote 8a8a8a
set -U fish_color_redirection 767676
